# Generated by Django 4.2.8 on 2023-12-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="author",
            table="author",
        ),
        migrations.AlterModelTable(
            name="chapter",
            table="chapter",
        ),
        migrations.AlterModelTable(
            name="comic",
            table="comic",
        ),
        migrations.AlterModelTable(
            name="comicauthor",
            table="comic_author",
        ),
        migrations.AlterModelTable(
            name="comictag",
            table="comic_tag",
        ),
        migrations.AlterModelTable(
            name="image",
            table="image",
        ),
        migrations.AlterModelTable(
            name="tag",
            table="tag",
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
