@host = http://localhost:8000

GET {{host}}/

### test
GET {{host}}/spider/test

### login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "name": "admin",
  "password": "admin"
}

###
POST {{host}}/regist HTTP/1.1
Content-Type: application/json

{
  "name": "admin",
  "password": "admin"
}

### spider
GET {{host}}/spider/test HTTP/1.1

