DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE comic (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  site TEXT NOT NULL,
  [desc] TEXT NOT NULL,
  url TEXT UNIQUE NOT NULL,
  name TEXT,
  len INTEGER,
);

CREATE TABLE chapter (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cid INTEGER NOT NULL,
  name TEXT,
  url TEXT UNIQUE NOT NULL,
  FOREIGN KEY (cid) REFERENCES comic (id)
);